### ISSUE TITLE
Cropped tool tip 

### ISSUE THREAD

**Issue by janukarhisa** [rhisa-tech/ohif_viewer#8]
There is a tool tip on the series menu and inside the image when some slices are missing. At the moment, it is left aligned and due to that, it is cropping. Can you align that to right?

<img width="218" alt="Screenshot 2023-05-15 at 10 04 54" src="https://github.com/rhisa-tech/ohif_viewer/assets/89907865/19cdc549-63ac-47d8-9cb6-104218544a1c">
<img width="119" alt="Screenshot 2023-05-15 at 10 05 15" src="https://github.com/rhisa-tech/ohif_viewer/assets/89907865/3ba0eed0-7069-4349-a3e1-f10841e44ab6">

**Comment by viranmalaka** [comment]
@janukarhisa could you please provide the steps to recreate this issue? a video might do a good job.

**Comment by janukarhisa** [comment]
@viranmalaka access this url : https://dicom-viewer.rhisa-eds-staging.eu/viewer/1.3.6.1.4.1.57771.26637316686142804
